#ifndef CURRENT_SENSORS_H_     
#define CURRENT_SENSORS_H_
//BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
#include <Arduino.h>

//BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
class Motor_Current_Sensors
{
    private:
        uint8_t _sensor_pin;
        float _calibration;
    public:
        Motor_Current_Sensors(uint8_t Connection_Pin, float calibration = 30.0);
        float Read();
};
//BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
#endif // !CURRENT_SENSORS_H_