#ifndef VOLT_SENSOR_H_     
#define VOLT_SENSOR_H_
//BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
#include <Arduino.h>
//BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

class Motor_Volt_Sensor
{
    private:
        uint8_t _pin;
        float _calibration;

    public:
        Motor_Volt_Sensor(uint8_t pin, float calibration = 311.0);
        float Read();
};
//BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
#endif // !VOLT_SENSOR_H_