#ifndef FLOW_RATE__SENSORS_H_     
#define FLOW_RATE__SENSORS_H_
//BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
#include <Arduino.h>
//BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
class Pump_Flow_Rate_Sensor
{
    private:
        uint8_t _sensor_pin;
    public:
        Pump_Flow_Rate_Sensor(uint8_t Connection_Pin);
        float Read();
};
//BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
#endif // !FLOW_RATE__SENSORS_H_